config/routes.rb
Rails.application.routes.draw do
  resources :books do
      resources :reviews
      collection do
        get 'search'
        post 'search'
      end
  end
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :books_written)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def search
    searched_value = params[:search]
    @books = Book.where("title LIKE ? OR author LIKE ? OR summary LIKE ? OR category LIKE ?",
     "%#{searched_value}%","%#{searched_value}%","%#{searched_value}%","%#{searched_value}%")
    render 'search'
  end
  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :category, :summary)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:new, :create, :show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = @book.reviews.build
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @book.reviews.create(review_params)
    @review.save
    redirect_to book_path(@book)
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    book = Book.find(params[:book_id])
    @review = book.reviews.find(params[:id])
    @review.destroy
    redirect_to book_path(book)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :books_written %>
    <%= f.text_area :books_written %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Books written</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.books_written %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Books written:</strong>
  <%= @author.books_written %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= bootstrap_form_for @book do |f| %>
 <%= f.text_field :title %>
 <%= f.text_field :author %>
 <%= f.text_field :category %>
 <%= f.text_area :summary %>
 <%= f.submit 'Save'%>
<% end %>

app/views/books/_search_form.html.erb
<%= form_for :search, url: search_books_path, method: "POST" do |f| %>

<%= text_field_tag "search", nil, placeholder:"enter your search here" %>
<%= submit_tag "search" %>
<%end%>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<section class="container-fluid main-container">
<article class="row book-content">

<% @books.each do |book| %>
<%= content_tag(:div, class: 'col-xs-4 book-container') do %>

<header class="book-title">
        <%= book.title %>
</header>
<section class="book-author-category">
      <div class="book-author">by <%= book.author %></div>
      <div class="book-category"> <%= book.category %></div>
</section>
<section class="book-summary">
        <%= book.summary %>
</section>
<footer class="book-links">
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        <%= link_to 'Reviews', book_path(book) %>
  <span>&nbsp&nbsp&nbsp</span>
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <%= link_to 'Edit', edit_book_path(book) %>
  <span>&nbsp&nbsp&nbsp</span>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <%= link_to 'Delete Book', book, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <% end %>

</footer>

</article>
</section>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<section class="container form-box">
<% @books.each do |book| %>
  <header class="book-search-title">
    <div class="book-search_title">Title</div>
    <br />
    <%= book.title %>
  </header>
  <section class="book-search-author">
    <div class="book-search-author-title">Author</div>
    <br />
    <%= book.author %>
  </section>

  <section class="book-search-category">
    <div class="book-search-category-title">Category</div>
    <br />
    <%= book.category %>
  </section>
  <section class="book-search-summary">
    <div class="book-search-summary-title">Summary</div>
    <br />
    <%= book.summary %>
  </section>
<% end %>
</section>

app/views/books/show.html.erb
<section class="container-fluid book-review">
    <section class="col-xs-6 book_summary">
        <section class="book-title">
            <%= @book.title %>
        </section>

        <section class="book-author">
            Author:
            <%= @book.author %>
        </section>

        <section class="book-category">
            Category:
            <%= @book.category %>
        </section>
        <section class="book-summary">
            <%= @book.summary %>
        </section>
        <br />
        <footer class="bottom-edit">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            <%= link_to 'Edit', edit_book_path(@book) %>
        </footer>
    </section>
    <section class="col-xs-6 book_review">
        <section class="book-review-title">Reviews</section>
        <% @book.reviews.each do |review| %>
        <section class="book-review-name">
            <strong><%= review.name %></strong>
        </section>

        <section class="book-review-content">
            <%= review.content %>
        </section>
        <br />
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>

        <%= link_to 'Edit', edit_book_review_path(@book, review) %>
        <span>&nbsp&nbsp&nbsp</span>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <%= link_to 'Delete', book_review_path(@book, review), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
    </section>
</section>
<footer class="page-footer">
    <%= link_to 'Add a new review', new_book_review_path(@book) %>
    <br/>
    <br/>
    <%= link_to 'Back', books_path, class:"btn btn-default"%>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Book Review</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    </head>

    <body class="container-fluid">
        <header class="container container-full">
            <section class="website-header">
                <strong>Ash's World of Books</strong>
            </section>
            <section class="create-book">
                <%= link_to 'Add a book here', new_book_path, class:"btn btn-default btn-create" %>
            </section>
            <section class="search-bar">
                <%= render 'search_form' %>
            </section>
        </header>
        <%= yield %>
    </body>
</html>

app/views/reviews/_form.html.erb
<section class="container review-form">
<%= bootstrap_form_for ([@book,@book.reviews.build]) do |f| %>
 <%= f.text_field :name %>
 <%= f.text_field :content %>
 <%= f.submit 'Save'%>
 <br />
 <%= link_to 'Back', books_path %>
<% end %>
</section>

app/views/reviews/_search_form.html.erb
<%= form_for :search, url: search_books_path, method: "POST" do |f| %>

<%= text_field_tag "search", nil, placeholder:"enter your search here" %>
<%= submit_tag "search" %>
<%end%>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= form_for ([@book,@review]) do |f| %>

        <p>
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </p>



        <p>
            <%= f.label :content %><br>
            <%= f.text_area :content %>
        </p>


        <%= f.submit 'Submit' %>
        <% end %>


<%= link_to 'Show', @book %> |
<%= link_to 'Back', book_path(@book) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="container header">
<h1>New Review</h1>
</div>
<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>